---
- include_tasks: setup_zabbix.yml

- include_tasks: setup_Debian7.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "7"

- include_tasks: setup_Debian.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version != "7"

- name: Copy rsyslog config for nginx
  copy:
    src: ../files/etc/rsyslog.d/nginx.conf
    dest: /etc/rsyslog.d/nginx.conf
  notify: restart rsyslog

- name: Inser in /etc/rsyslog.conf use module imfile
  lineinfile:
    path: /etc/rsyslog.conf
    insertafter: "^(.*)provides support for local system logging(.*)$"
    line: 'module(load="imfile" mode="inotify")'
  notify: restart rsyslog


- name: Copy logrotate config for logs from rsyslog
  copy:
    src: ../files/etc/logrotate.d/nginx_rsyslog
    dest: /etc/logrotate.d/nginx_rsyslog

- name: Replace in zabbix_agent.conf ServerActive
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^ServerActive=(.+)$'
    replace: 'ServerActive=monitoring.it-oblako.ru:30051'
  notify: restart zabbix-agent


- name: Replace in zabbix_agent.conf MaxLinesPerSecond
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^( *)MaxLinesPerSecond=(\w+)$'
    replace: 'MaxLinesPerSecond=1000'
  register: zabbix_maxlines
  notify: restart zabbix-agent


- name: Replace in zabbix_agent.conf MaxLinesPerSecond
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^#( *)MaxLinesPerSecond=(\w+)$'
    replace: 'MaxLinesPerSecond=1000'
  when: zabbix_maxlines.changed == false
  notify: restart zabbix-agent


- name: Replace in /etc/logrotate.d/nginx create 640 nginx adm
  replace:
    path: /etc/logrotate.d/nginx
    regexp: '^(.*)create ?640 (\S*) adm$'
    replace: '\tcreate 644 nginx adm'

- name: Inser in /etc/rsyslog.conf use module imfile
  lineinfile:
    path: /etc/rsyslog.conf
    insertafter: "#### MODULES ####\n\r#################"
    line: 'module(load="imfile" mode="inotify")'

# - lineinfile:
#     path: /etc/nginx/nginx.conf
#     regexp: 'log_format main(.*);$'
#     line: 'log_format main \'$host $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" $request_time\';'
#   notify: restart nginx
