---
- name: Install a .deb package zabbix-release_3.4 from the internet.
  apt:
    deb: https://repo.zabbix.com/zabbix/3.4/{{ ansible_distribution | lower }}/pool/main/z/zabbix-release/zabbix-release_3.4-1+{{ ansible_distribution_release }}_all.deb

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=600

- name: Install zabbix-agent package(s)
  apt:
    pkg: zabbix-agent
    state: latest
    force: yes
    install_recommends: yes
