---
- name: install the zabbix-release-3.4 rpm from a remote repo 
  yum:
    name: https://repo.zabbix.com/zabbix/3.4/rhel/6/x86_64/zabbix-release-3.4-1.el6.noarch.rpm
    state: present
  when: ansible_distribution_major_version == "6"

- name: install the zabbix-release-3.4 rpm from a remote repo
  yum:
    name: https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm
    state: present
  when: ansible_distribution_major_version == "7"

- name: upgrade zabbix-agent package
  yum:
    name: 'zabbix-agent'
    state: latest
