---
- name: Enable Backports repository (Debian).
  apt_repository:
    repo: 'deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main'
    state: present
    filename: "{{ ansible_distribution_release }}_backports"

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=600

- name: Install rsyslog package(s)
  apt:
    pkg: rsyslog
    state: latest
    force: yes
    install_recommends: yes
    only_upgrade: yes
    default_release: "{{ansible_distribution_release}}-backports"
